# fly.toml app configuration file generated for camerabot on 2024-01-28T10:25:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'camerabot'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 8080

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
